version: '3.8'

networks:
  mongodb-net:
    driver: bridge

volumes:
  mongo_data:

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - mongodb-net
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  compass-web:
    image: haohanyang/compass-web
    container_name: compass-web
    networks:
      - mongodb-net
    ports:
      - "8080:8080"
    environment:
      CW_MONGO_URI: "mongodb://root:password@mongo:27017"
    depends_on:
      - mongo