version: '3.8'

networks:
  redis-net:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - redis-net
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
    command: redis-server --requirepass password

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    networks:
      - redis-net
    ports:
      - "5540:5540"
    depends_on:
      - redis